plugins {
    id 'base'
}

group = mod_group_id
version = mod_version

allprojects {
    tasks.withType(org.gradle.api.tasks.bundling.AbstractArchiveTask).configureEach {
        preserveFileTimestamps = false
        reproducibleFileOrder = true
    }
}

def commonProjectPath = ':platforms:mc1_20_1:common'
def fabricProjectPath = ':platforms:mc1_20_1:fabric'
def forgeProjectPath = ':platforms:mc1_20_1:forge'
def mc1211CommonProjectPath = ':platforms:mc1_21_1:common'
def mc1211FabricProjectPath = ':platforms:mc1_21_1:fabric_1_21_1'
def mc1211ForgeProjectPath = ':platforms:mc1_21_1:forge_1_21_1'
def mc1211NeoForgeProjectPath = ':platforms:mc1_21_1:neoforge_1_21_1'

tasks.register('test') {
    group = LifecycleBasePlugin.VERIFICATION_GROUP
    description = 'Runs all unit tests.'
    dependsOn ':core:test', "${commonProjectPath}:test", "${fabricProjectPath}:test", "${forgeProjectPath}:test", "${mc1211CommonProjectPath}:test", "${mc1211FabricProjectPath}:test", "${mc1211ForgeProjectPath}:test", "${mc1211NeoForgeProjectPath}:test"
}

tasks.named('check') {
    dependsOn ':core:check', "${commonProjectPath}:check", "${fabricProjectPath}:check", "${forgeProjectPath}:check", "${mc1211CommonProjectPath}:check", "${mc1211FabricProjectPath}:check", "${mc1211ForgeProjectPath}:check", "${mc1211NeoForgeProjectPath}:check"
}

tasks.named('assemble') {
    dependsOn ':core:assemble', "${commonProjectPath}:assemble", "${fabricProjectPath}:assemble", "${forgeProjectPath}:assemble", "${mc1211CommonProjectPath}:assemble", "${mc1211FabricProjectPath}:assemble", "${mc1211ForgeProjectPath}:assemble", "${mc1211NeoForgeProjectPath}:assemble"
}

tasks.named('build') {
    dependsOn "${mc1211CommonProjectPath}:build", "${mc1211FabricProjectPath}:build", "${mc1211ForgeProjectPath}:build", "${mc1211NeoForgeProjectPath}:build"
}
