org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
org.gradle.parallel=true
org.gradle.caching=true

parchment_minecraft_version=1.21.1
parchment_mappings_version=2024.11.17
minecraft_version=1.21.1
minecraft_version_range=[1.21.1]
neo_version=21.1.235
loader_version_range=[1,)

mod_id=areamusic
mod_name=AreaMusic
mod_license=All Rights Reserved
mod_version=0.0.1
mod_group_id=datura
mod_authors=Datura
mod_description=Play local music automatically inside server-defined areas.
