pluginManagement {
    repositories {
        gradlePluginPortal()
        maven {
            name = 'Fabric'
            url = 'https://maven.fabricmc.net/'
        }
        maven {
            name = 'NeoForged'
            url = 'https://maven.neoforged.net/releases/'
        }
    }
}

plugins {
    id 'org.gradle.toolchains.foojay-resolver-convention' version '1.0.0'
}

rootProject.name = 'areamusic'

include ':core'
include ':platforms:mc1_20_1:common'
include ':platforms:mc1_20_1:fabric'
include ':platforms:mc1_20_1:forge'
include ':platforms:mc1_21_1:common'

project(':platforms').projectDir = file('platforms')
project(':platforms:mc1_20_1').projectDir = file('platforms/1.20.1')
project(':platforms:mc1_20_1:common').projectDir = file('platforms/1.20.1/common')
project(':platforms:mc1_20_1:fabric').projectDir = file('platforms/1.20.1/fabric')
project(':platforms:mc1_20_1:forge').projectDir = file('platforms/1.20.1/forge')
project(':platforms:mc1_21_1').projectDir = file('platforms/1.21.1')
project(':platforms:mc1_21_1:common').projectDir = file('platforms/1.21.1/common')
