plugins {
    id 'java-library'
}

group = rootProject.group
version = rootProject.version

java {
    toolchain.languageVersion = JavaLanguageVersion.of(17)
}

repositories {
    mavenCentral()
}

dependencies {
    compileOnlyApi 'com.google.code.gson:gson:2.10'

    implementation('com.googlecode.soundlibs:mp3spi:1.9.5.4') {
        transitive = false
    }
    implementation('com.googlecode.soundlibs:jlayer:1.0.1.4') {
        transitive = false
    }
    implementation('com.googlecode.soundlibs:vorbisspi:1.0.3.3') {
        transitive = false
    }
    implementation('com.googlecode.soundlibs:tritonus-share:0.3.7.4') {
        transitive = false
    }
    implementation('org.jflac:jflac-codec:1.5.2') {
        transitive = false
    }

    testImplementation platform('org.junit:junit-bom:5.10.2')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testImplementation 'com.google.code.gson:gson:2.10'
    testRuntimeOnly 'org.jcraft:jorbis:0.0.17'
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}

tasks.named('test', Test).configure {
    useJUnitPlatform()
}
